---
- hosts: webservers
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.apt: 
      name: nginx:latest 
      state: present
      
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
  - name: Install Node.js and npm
    ansible.builtin.apt:
      name:
        - nodejs
        - npm
      state: present
      
  - name: Copy Node.js Application files
    ansible.builtin.copy:
      src: Path_NodeJs_APP_FILES
      dest: /PATH/nodejs-app
  - name: Install Node.js application dependencies
    ansible.builtin.command: npm install
      args:
        chdir: /opt/nodejs-app

  - name: Configure Nginx as Reverse Proxy
    ansible.builtin.template:
      src: nginx.conf.j2  
      dest: /etc/nginx/sites-available/default
    notify:
      - Restart Nginx

  handlers:
  - name: Restart Nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
